id: IA2FFF7A9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T19:55:45+00:00'
last_modified: '2022-06-08T12:33:52.829334+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6001
  title: དཔལ་རྒྱལ་བ་ཇོ་ནང་པའི་ལྟ་བ་ཤན་འབྱེད་ཡིད་ཀྱི་མུན་སེལ་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3A85:
      image_group_id: I1KG6030
      title: ''
      total_pages: 238
      order: 1
      base_file: 3A85.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
